In [5]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("purchase_orders.csv")

print(df.head())

      PO_ID Supplier_ID Store_ID Product_ID  Order_Date  \
0  PO000001      SUP017     ST02      P0443  2025-02-02
1  PO000002      SUP057     ST06      P0313  2025-05-11
2  PO000003      SUP074     ST04      P0215  2025-09-17
3  PO000004      SUP064     ST02      P0118  2024-10-07
4  PO000005      SUP069     ST09      P0463  2025-10-08

  Expected_Delivery_Date Actual_Delivery_Date  Quantity_Ordered  \
0             2025-02-08           2025-02-08               121
1             2025-05-17           2025-05-17               207
2             2025-09-21           2025-09-21               554
3             2024-10-10           2024-10-10               574
4             2025-10-16           2025-10-21               436

   Purchase_Cost Delivery_Status
0        8725.52       Delivered
1       73750.52       Delivered
2       11422.64       Delivered
3      108335.91       Delivered
4       51411.60       Delivered

In [6]:
engine = create_engine(
    "mysql+pymysql://root:password@localhost:3306/Dmart_Analysis"
)

In [ ]:
df.to_sql(
    "purchase_orders",
    con=engine,
    if_exists="replace",   # Creates a new table
    index=False
)

In [2]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
stores = pd.read_csv("stores.csv")
suppliers = pd.read_csv("suppliers.csv")
purchase_orders = pd.read_csv("purchase_orders.csv")
inventory = pd.read_csv("inventory.csv")
sales = pd.read_csv("sales.csv")
categories = pd.read_csv("categories.csv")

In [7]:
customers.to_sql("customers", engine, if_exists="append", index=False)

products.to_sql("products", engine, if_exists="append", index=False)

stores.to_sql("stores", engine, if_exists="append", index=False)

suppliers.to_sql("suppliers", engine, if_exists="append", index=False)

categories.to_sql("categories", engine, if_exists="append", index=False)

inventory.to_sql("inventory", engine, if_exists="append", index=False)

purchase_orders.to_sql("purchase_orders", engine, if_exists="append", index=False)

sales.to_sql("sales", engine, if_exists="append", index=False)

250000

In [14]:
pd.read_sql("DESCRIBE sales;", engine)

               Field    Type Null Key Default Extra
0     Transaction_ID    text  YES        None
1   Transaction_Date    text  YES        None
2           Store_ID    text  YES        None
3        Customer_ID    text  YES        None
4         Product_ID    text  YES        None
5           Quantity  bigint  YES        None
6         Unit_Price  double  YES        None
7   Discount_Percent  double  YES        None
8       Sales_Amount  double  YES        None
9             Profit  double  YES        None
10      Payment_Mode    text  YES        None
11     Is_Bulk_Order    text  YES        None

Total Sales Per Store

In [19]:
import pandas as pd

query = """
SELECT
    Store_ID,
    SUM(Sales_Amount) AS Total_Sales
FROM sales
GROUP BY Store_ID
ORDER BY Total_Sales DESC;
"""

df = pd.read_sql(query, engine)
df

   Store_ID  Total_Sales
0      ST02  50328840.39
1      ST01  49047926.92
2      ST12  31617590.55
3      ST03  29398037.03
4      ST10  26236106.18
5      ST07  24319085.60
6      ST09  21717811.84
7      ST06  19564992.00
8      ST08  17670032.10
9      ST05  15418004.57
10     ST11  13790825.68
11     ST04  12341787.10

Top 10 Best Selling Products

In [22]:
query = """
SELECT
    s.Product_ID,
    p.Product_Name,
    SUM(s.Sales_Amount) AS Total_Sales,
    SUM(s.Quantity) AS Total_Quantity
FROM sales s
JOIN products p
ON s.Product_ID = p.Product_ID
GROUP BY s.Product_ID, p.Product_Name
ORDER BY Total_Quantity DESC
LIMIT 10;
"""

df = pd.read_sql(query, engine)
df

,Product_ID,Product_Name,Total_Sales,Total_Quantity
0,P0137,Tata Tea Tea Powder 250g - Variant 4,2307049.98,5456.0
1,P0117,Nescafe Instant Coffee 50g - Variant 2,85174.36,5412.0
2,P0102,Bisleri Soda Water 600ml,2115354.99,5200.0
3,P0119,Pepsi Lemon Drink 600ml - Variant 2,2030197.00,4826.0
4,P0121,Fanta Cold Drink 1.25L - Variant 3,1565970.52,4728.0
5,P0120,Thums Up Cold Drink 750ml - Variant 3,721115.08,4709.0
6,P0125,Pepsi Energy Drink 250ml - Variant 3,1683012.75,4655.0
7,P0133,Tropicana Packaged Juice 1L - Variant 4,925809.01,4587.0
8,P0132,Fanta Cold Drink 1.25L - Variant 4,1119656.69,4583.0
9,P0118,Red Label Green Tea 100g - Variant 2,954116.10,4572.0

Monthly Sales Trend

In [29]:
query = """
SELECT
    YEAR(STR_TO_DATE(Transaction_Date, '%%Y-%%m-%%d')) AS Year,
    MONTH(STR_TO_DATE(Transaction_Date, '%%Y-%%m-%%d')) AS Month,
    SUM(Sales_Amount) AS Total_Sales
FROM sales
GROUP BY
    YEAR(STR_TO_DATE(Transaction_Date, '%%Y-%%m-%%d')),
    MONTH(STR_TO_DATE(Transaction_Date, '%%Y-%%m-%%d'))
ORDER BY Year, Month;
"""

df = pd.read_sql(query, engine)
df

    Year  Month  Total_Sales
0   2023      1   8114860.06
1   2023      2   7043145.27
2   2023      3   9410712.46
3   2023      4   8198619.79
4   2023      5   8658662.34
5   2023      6   7564441.50
6   2023      7   8602559.41
7   2023      8   8357572.11
8   2023      9   8706492.66
9   2023     10   7897779.71
10  2023     11  12267637.98
11  2023     12   8269184.43
12  2024      1   8176551.09
13  2024      2   7378051.53
14  2024      3   9698598.00
15  2024      4   8658142.10
16  2024      5   8219526.15
17  2024      6   7623180.94
18  2024      7   8922620.83
19  2024      8   9350609.16
20  2024      9   8000540.55
21  2024     10   9715014.71
22  2024     11  10533695.17
23  2024     12   8448683.09
24  2025      1   7742217.14
25  2025      2   7145068.16
26  2025      3   9456728.45
27  2025      4   8300484.43
28  2025      5   7755153.81
29  2025      6   7865963.08
30  2025      7   8420669.99
31  2025      8   9534622.25
32  2025      9   8357144.93
33  2025     10  12560125.29
34  2025     11   8125009.60
35  2025     12   8370971.79

Top 10 Customers by Total Spending

In [30]:
query = """
SELECT
    c.Customer_ID,
    c.Customer_Name,
    SUM(s.Sales_Amount) AS Total_Spent,
    COUNT(s.Transaction_ID) AS Total_Orders
FROM sales s
JOIN customers c
ON s.Customer_ID = c.Customer_ID
GROUP BY
    c.Customer_ID,
    c.Customer_Name
ORDER BY Total_Spent DESC
LIMIT 10;
"""

df = pd.read_sql(query, engine)
df

  Customer_ID       Customer_Name  Total_Spent  Total_Orders
0      C12095           Neel Dani    516119.56            85
1      C01956         Yug Singhal    502435.93            67
2      C01596         Imaran Gala    456097.93            46
3      C06798          Amrita Oak    447422.10           103
4      C12372         Ekaja Bains    438090.61            66
5      C08755          Omaja Virk    437982.43            85
6      C01334         Faraj Reddy    431153.75            62
7      C12189        Qabil Kamdar    409496.70            71
8      C08874           Reva Buch    400715.35            80
9      C04271  Frederick Majumdar    391753.40            56